version: '2.4'
services:
  server:
    build: .
    ports:
      - "3804:3804"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3804/"]
      interval: 10s
      timeout: 5s
      retries: 3
  client:
    image: curlimages/curl:7.84.0
    command: "curl -s --output /dev/null 'http://server:3804'"
    depends_on:
      server:
        condition: service_healthy
  benchmark:
    image: jordi/ab
    command: "ab -n 100 -c 100 http://server:3804/"
    depends_on:
      server:
        condition: service_healthy

  
