#!/bin/bash

sudo apt update -y
sudo apt install tmux -y

export GOBIN="$(pwd)/bin"
export GOBIN="/go/bin"

echo 'export PATH="$PATH:$GOBIN"' >> ~/.bashrc


go install github.com/cosmtrek/air@latest
 go install github.com/clipperhouse/gen@latest

curl https://wazero.io/install.sh | sh
cp ./bin/wazero $GOBIN/wasm
# alias wasm="$(pwd)/bin/wazero"
curl https://wasmtime.dev/install.sh -sSf | bash

source ~/.bashrc

curl -sSf https://raw.githubusercontent.com/owenthereal/goup/master/install.sh | sh -s -- '--skip-prompt'

source $HOME/.go/env

goup install

echo 'export PATH="$PATH:/home/codespace/.go/bin"' >> ~/.bashrc
echo 'export PATH="$PATH:/home/codespace/.go/current/bin"' >> ~/.bashrc
echo 'unset GOROOT' >> ~/.bashrc


source ~/.bashrc

goup version

goup ls

sudo rm -rf /usr/local/go

unset GOROOT

go env GOROOT

go version

goup upgrade

# goup install tip &
# goup install 1.13 &
# goup install 1.14 &
# goup install 1.15&
# goup install 1.16 &
# goup install 1.17 &
# goup install 1.18 &
# goup install 1.19 &

# goup set

# goup search #list all golang versions

tmux new-session -d -s mysession
tmux split-window -h -t mysession:0

commands=("goup install tip" "goup install 1.13" "goup install 1.14" "goup install 1.15" "goup install 1.16" "goup install 1.17" "goup install 1.18" "goup install 1.19","goup install 1.20")

for i in "${commands[@]}"; do
    tmux select-pane -t mysession:0
    tmux split-window -h -t mysession:0
    tmux send-keys "$i" Enter
done

tmux select-pane -t mysession:0
tmux attach-session -t mysession


tmux new-session -d -s install-go

# Splitting the first pane horizontally
tmux split-window -h -t install-go:0

# Splitting the first pane vertically
tmux split-window -v -t install-go:0

# Splitting the second pane vertically
tmux split-window -v -t install-go:1

commands=("goup install tip" "goup install 1.13" "goup install 1.14" "goup install 1.15" "goup install 1.16" "goup install 1.17" "goup install 1.18" "goup install 1.19")

for i in "${commands[@]}"; do
    tmux select-pane -t install-go:0
    tmux split-window -v -t install-go:0
    tmux send-keys "$i" Enter
done

tmux select-pane -t install-go:0
tmux attach-session -t install-go

go install github.com/traefik/yaegi/cmd/yaegi@latest